# This is a basic workflow to help you get started with Actions

name: mirror-test

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  mirror-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          ssh_private_key: ${{ secrets.SSH_SECRET }}
          target_repo_url: ${{ secrets.REPO }}
  build:
    needs: mirror-checkout
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.3.8'
    - run: pwd
    - run: ls
    - run: cd mirror-test
    - run: pwd
    - run: ls
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: main
        tag: v1.0.${{ github.run_number }}
